### PR TITLE
Adds inline certificate support for .ovpn files

### PR DESCRIPTION
**Pull request by urosorozel**

### CODE REVIEW

**Comment by robbintt** [comment]
Hi, this is interesting but does not belong in this ansible role. This should go in a different ansible role which consumes this role. Please check out my ansible playbook for a similar role: https://github.com/robbintt/popup-openvpn

**Comment by urosorozel** [comment]
Hey,

this role is already creating .ovpn files with respective client filename certs, the only difference here is that we can store the certificate contents in the .ovpn file and don't need to worry about them.

**Comment by robbintt** [comment]
I think it would be best to keep this role as simple as possible to support many versatile configurations.  In your case you would write a second ansible role to do complex tasks like merging and moving configurations. 

I read your code and I think it's neat but I think it belongs in a separate role following a similar pattern to this role I wrote in popup-openvpn: https://github.com/robbintt/popup-openvpn/blob/master/roles/makeovpn/tasks/main.yml

A number of configurations don't inline these files. While creating the ovpn is necessary, putting the certificates inline is optional based on the openvpn client you are using.

**Comment by conorsch** [comment]
It seems worthwhile to me to support inline configs like this, since it makes bootstrapping new connections to much easier. However I'd much prefer a method that was opt-in, would would satisfy most of @robbintt's concerns about complexity. 

I'll take a crack at an alternative configuration that allows admins to selectively enable creating an ovpn config file with the cert and ca info inlined, then tag you in it for review, @urosorozel.

**Comment by conorsch** [comment]
@urosorozel likes the superseding changes proposed in #56, so closing this PR.

**Pull request closed without merging**
