### PR TITLE
Fix pam.d config on CentOS

### PR DESCRIPTION
**Pull request by zuccon**
Template a working pam.d config on 'RedHat' type systems.

### CODE REVIEW

**Comment by nkakouros** [comment]
I think it would be better to have the conditional in the template and use and `include` statement there to include the login configuration. 

I am not so familiar with PAM, so let me ask. Doesn't the `login` configuration contain many more things than what is needed for openvpn? If this is true, is this going to be an issue?

**Comment by zuccon** [comment]
It definitely contains more than required, don't think it's going to be an issue, but updated the PR without what's unnecessary, also moved condition to the template. Though about it before but the "include" statements don't work on CentOS, this other syntax works though, and does the same thing.

**Comment by nkakouros** [comment]
Thanks for the clarification! Could you use `elif` instead of the nested `if`? Sth else, why do we need to restart openvpn now after pam configuration is in place?

**Comment by zuccon** [comment]
There is another condition which doesn't show up in the diff, checked against `openvpn_use_pam_users`.
That doesn't work anyways in CentOS as the `pam_pwdfile` module is not present and only provided by non-epel third party repos.
So, updated it this way.

You're right about the restart, I did some testing before and saw that it required restart but it doesn't, removed it.

**Comment by nkakouros** [comment]
Thanks for your work! Right now, no testing is done against CentOS. I think it fails currently. Would you be interested in helping out pinpoint the cause?

**Comment by zuccon** [comment]
thank you! sure, what do you mean by "it fails"? I just deployed on CentOS, this was the only issue I've found, but can test something specific if required.

**Comment by nkakouros** [comment]
Could you git-pull the role again, and use molecule to run the tests?

```
pip install molecule
cd path/to/role
MOLECULE_DISTRO=centos7 molecule test
```

I updated travis too. The tests fail when starting the openvpn server. Maybe it is sth docker specific, but I didn't have the time to look into it.

**Pull request merged**
