### PR TITLE
Make ansible-lint happy

### PR DESCRIPTION
**Pull request by alexclear**

### CODE REVIEW

**Comment by nkakouros** [comment]
Thank you for this.

First, I was the one that transformed all those conditionals to direct comparisons. The reason was my hasty interpretation of this warning that the devel version of ansible throws:

```
[DEPRECATION WARNING]: evaluating openvpn_use_pam as a bare variable, this
behaviour will go away and you might need to add |bool to the expression in the
 future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature
will be removed in version 2.12. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
```

Instead of adding `| bool` I thought I should add direct comparisons.. :-/

This brings me to the awkward situation of asking you if possible to add `| bool` to those conditionals, so that the role is future-proof. 

Second, it is worrisome that the tests did not raise a flag with the tests. I wonder why this is the case. Even on my machine, `ansible-lint` did not complain. I then made sure I had installed the latest version with `pip3` and it worked as expected. Any thoughts on the tests failing on us?

**Comment by alexclear** [comment]
Hmm, I can't get this deprecation warning on my setup, what Ansible version are you using?
I'm on 2.7.8.
I think I know a root cause of this but I can't check since I don't get the warning.
Regarding `ansible-lint` and its inability to detect anything under `molecule`, I slightly modified the molecule config to force ansible-lint to print its effective ruleset:
https://travis-ci.org/kofonfor/Stouts.openvpn/jobs/497609171#L648-L680
It turns out there are only 16 rules in ansible-lint 3.4.23, and I'm on ansible-lint 4.1.0 locally, it has 31 rules in its ruleset.
I'm going to check how to add the most recent `ansible-lint` to molecule setup, probably `pip` will do the job.

**Comment by nkakouros** [comment]
That clears it up. 

I am using a weekly checkout of ansible's devel branch, so I would say I am on 2.8 alpha.

**Comment by alexclear** [comment]
Okay, just checked, ansible-lint v. 4.1.0 worked as expected on the develop branch:
https://travis-ci.org/kofonfor/Stouts.openvpn/jobs/497615606#L679-L821
I used pip to install it like this:
https://github.com/kofonfor/Stouts.openvpn/blob/molecule-ansible-lint/.travis.yml#L16
I am going to check deprecation warnings using latest Ansible devel branch.

**Comment by nkakouros** [comment]
Awesome! Waiting for the results!

**Comment by elaske** [comment]
Looks like this has passed and would fix `develop`, no?

**Comment by nkakouros** [comment]
I am not sure `when: (openvpn_use_external_repo)` is the way to go. I would prefer `when: openvpn_use_external_repo | bool`. 

@alexclear What do you think?

**Comment by nkakouros** [comment]
I went with the suggestion from the ansible warning itself and added `| bool` in 441584906013d416cc3ad94bb48375d21d10f667.

**Pull request closed without merging**
