### PR TITLE
Stretch support and improvements

### PR DESCRIPTION
**Pull request by HanXHX**
Hi!

This PR provides Stretch support (avoid Ansible/Python bugs).
It removes the hard dependency to systemd (`openvpn_service`).

Cheers!

HanXHX

### CODE REVIEW

**Comment by asosso** [comment]
why isn't it yet merged?

**Comment by JOGUI22** [comment]
Please merge this. It saved my day.

**Comment by HanXHX** [comment]
@JOGUI22 I'll fork and maintain this project soon... With new features, compat with newer Ansible versions, CI... etc.

**Comment by nkakouros** [comment]
@HanXHX No need for a fork. 

I was given commit access to this repo a couple of months ago. I am currently switching automated testing to molecule. After molecule was in place, only then did I plan to merge this PRs so as to avoid merging broken code. I was expecting this to be done sooner but life got in the way. As people are getting impatient, I will go ahead and merge a couple of the most popular PRs right now and test them later, fixing in the process what needs to be fixed.

**Comment by JOGUI22** [comment]
I'm very happy for the fast answer @tterranigma and @HanXHX . For what I tested yesterday, everything is fine with this pull request. @tterranigma proceed as you wish, it's also important to be serious with your git discipline :)

Happy weekend,

**Pull request merged**
