### PR TITLE
Allow explicit configuration of server dev

### PR DESCRIPTION
**Pull request by mowgli**
Allow to configure different device for server (eg. tun0 for routing).

### CODE REVIEW

**Comment by conorsch** [comment]
Role default behavior doesn't change, but the new var should be documented. @mowgli can you move the new var to role defaults and update the README vars?

**Comment by mowgli** [comment]
I can document it, sure.

But the idea is that it is undefined when not in use. However, an empty string would serve the same. It just wouldn't be that elegant. ;-)

**Comment by conorsch** [comment]
I don't expect to use the new var myself, but if it is supported by the role, then it should be exposed in the default vars, so other users can discover it.

**Comment by conorsch** [comment]
To be clear, I was thinking something like:

```
openvpn_dev: tun
# Optional override specifically for server interface
openvpn_server_dev: "{{ openvpn_dev }}"
```

Then the template doesn't need to change at all. Oh, and please politely use postfix comments as is the custom for this role. :grin:

**Comment by mowgli** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

I just pushed two more commits, one to also use the right dev in bridge
setup and second to document it.
- -- 
Klaus Ethgen                                       http://www.ethgen.ch/
pub  4096R/4E20AF1C 2011-05-16            Klaus Ethgen <Klaus@Ethgen.ch>
Fingerprint: 85D4 CA42 952C 949B 1753  62B3 79D0 B06F 4E20 AF1C
-----BEGIN PGP SIGNATURE-----
Comment: Charset: ISO-8859-1

iQGzBAEBCgAdFiEEMWF28vh4/UMJJLQEpnwKsYAZ9qwFAliUSnoACgkQpnwKsYAZ
9qywDgwAlv/IdJSpjjh6sbVWrTB5vjqBAkcZjGX6pFV2SSpjbPiX1XjGSxnqvSfT
z97T4hiUuFQU5wXXkzjxPrcX4k+OMNzx0ZeqQZtJ+4MQxUhunGyyVFSKl6suoPu9
4w0XFs9MptMBfGZskjQDJFxfRgUjsUBId0BhYhN5W8MEkAVp7E3L/whAQTnKmWK7
oFqAi8WtKOQ2eDECYckTWmKsy3Lj+/OjcIV3A8xeZrGgAEobK3mTJGGF/Sk6SvnK
GdZEanE2aHFuKEy3Gu6O3CtTnHWa/HxO5ryFl+yz0GskrKP8UFqm8iYZA8fLdgZh
J9xM0MGSPzQeZBnyF5N3hT4zivj2AoqZG7vCi6muvlBLisCLp9v50rGiJAO5U7ZV
4/TY7kXxjkiRBLZFV8tFJPt3cHvtS4HcRX6Vo6KyM65pxGk5Rl9aI+icEIXw5kph
qa00uBCGpH+ebJBu7nJ0bOmcfvt1UTgJpZzprc3qzYAn94/1sKRPHsPWE1ky18wF
1Kbx4YdF
=8JpZ
-----END PGP SIGNATURE-----

**Pull request closed without merging**
