### PR TITLE
Add a handler to be used by other roles after openvpn is done

### PR DESCRIPTION
**Pull request by jaysonsantos**
With this other roles could listen to this handler and react to backup
the keys somewhere else

### CODE REVIEW

**Comment by jaysonsantos** [comment]
I also changed the idempotency counter because notify will always trigger it. Let me know if you would like to trigger the notify only if one of the steps actually changed.

**Comment by nkakouros** [comment]
I wonder if setting a variable like `openvpn_run` is simpler. The handler seems mor "programmatic", but compared to the variable it adds one more task and has the idempotency issues.

**Comment by jaysonsantos** [comment]
Hey there, sorry for the long delay. Where do you think this should be called, inside the handler itself? Or adding a new handler here https://github.com/Stouts/Stouts.openvpn/blob/develop/handlers/main.yml to listen to `openvpn pack clients`?

**Comment by nkakouros** [comment]
I was thinking of not doing anything with handlers, but simply the very last task of this role to be a `set_fact` tasks that sets an `openvpn_complete` or `openvpn_run` variable to `true`. Any other role can check that variable. 

Your approach using handlers feels cooler and more programmatic but it breaks idempotency which is a core design principle of Ansible playbooks. Plus, it adds a "noop" task that adds (a tiny) overhead.

**Comment by nkakouros** [comment]
I will close this due to the reasons explained above. Thank you for your effort and the idea behind this PR. Please, do open a new PR if you believe the variable approach is of interest to you.

**Pull request closed without merging**
